name: Launch workshop
description:
  Install Workshop and use it to launch an ephemeral development environment
author: Canonical
branding:
  icon: tool
  color: orange
inputs:
  token:
    description: Access token for canonical/workshop.
    required: true
  version:
    description: Workshop version or range of versions.
    default: latest
  project:
    description: Directory containing a workshop to launch.
  workshop:
    description: Name of workshop to launch.
  cache:
    description: Mount plugs to cache across workflow runs.
runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
  post-if: success()
