name: Test Workshop compatibility

on:
  schedule:
    - cron: '00 6 * * 4,5'
  workflow_dispatch:

jobs:
  build-snap:
    name: Build Workshop snap
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workshop
        uses: actions/checkout@v6
        with:
          repository: canonical/workshop
          token: ${{ secrets.WORKSHOP_TOKEN }}
          fetch-depth: 0

      - name: Build Workshop snap
        uses: canonical/action-build@v1
        id: snapcraft

      - name: Upload Workshop snap
        uses: actions/upload-artifact@v7
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

  os-tests:
    name: OS tests
    needs: build-snap
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        workshop: [focal, jammy, noble]

    steps:
      # The Action can only download released versions of Workshop, but we can
      # make it use a development snap by putting it in the tool cache. This
      # hack can be removed once we start publishing snaps for the main branch.
      - name: Create tool cache
        run: |
          arch="$(node -e 'console.log(process.arch)')"
          path="${RUNNER_TOOL_CACHE}/workshop/0.1.0/${arch}"
          printf 'path=%s\n' "$path" >> "$GITHUB_OUTPUT"

          mkdir -p "$path"
          touch "${path}.complete"
        id: tool_cache

      - name: Download Workshop Snap
        uses: actions/download-artifact@v8
        with:
          name: snap
          path: ${{ steps.tool_cache.outputs.path }}

      - name: Checkout
        uses: actions/checkout@v6

      - name: Launch workshop
        uses: canonical/launch-workshop@v0
        with:
          token: ${{ secrets.WORKSHOP_TOKEN }}
          version: '0.1.0'
          workshop: ${{ matrix.workshop }}

      - name: Check base image
        run: |
          release="$(workshop exec "$WS" lsb_release --codename --short)"
          [ "$WS" = "$release" ]
        env:
          WS: ${{ matrix.workshop }}
