name: Check for fixup and squash commits

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    # https://github.com/canonical/workshop/pull/675
    uses: canonical/workshop/.github/workflows/fixup.yaml@3202bf592e2251561c97664162d04b377192ec62
