name: Check for fixup and squash commits

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    # https://github.com/canonical/workshop/pull/675
    uses: canonical/workshop/.github/workflows/fixup.yaml@6e4a09ba299f29c547586855711e6f66010cc9af
