name: Check for fixup and squash commits

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    # https://github.com/canonical/workshop/pull/675
    uses: canonical/workshop/.github/workflows/fixup.yaml@5832ca931f966c789b42d7e16928ce84af874abf
