name: Automatic tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

  os-tests:
    name: OS tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        workshop: [focal, jammy, noble]
    environment:
      name: workshop
      deployment: false

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Launch workshop
        uses: ./
        with:
          token: ${{ secrets.WORKSHOP_TOKEN }}
          workshop: ${{ matrix.workshop }}

      - name: Check base image
        run: |
          release="$(workshop exec "$WS" lsb_release --codename --short)"
          [ "$WS" = "$release" ]
        env:
          WS: ${{ matrix.workshop }}

  prepare-cache:
    name: Prepare cache
    runs-on: ubuntu-latest
    environment:
      name: workshop
      deployment: false
    outputs:
      path: ${{ steps.copy.outputs.path }}
      one: ${{ steps.write.outputs.one }}
      two: ${{ steps.write.outputs.two }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Copy project to unique location
        id: copy
        run: |
          path="prj-$(openssl rand -hex 8)"
          mkdir "$path"
          cp -a .workshop "$path"
          printf 'path=%s\n' "$path" >> "$GITHUB_OUTPUT"

      - name: Launch workshop
        uses: ./
        with:
          token: ${{ secrets.WORKSHOP_TOKEN }}
          project: ${{ steps.copy.outputs.path }}
          workshop: cache
          cache: |
            cache:one
            cache:two

      - name: Generate cached data
        id: write
        run: |
          for plug in one two; do
            value="$(openssl rand -hex 8)"
            workshop run cache write "$plug" "$value"
            printf '%s=%s\n' "$plug" "$value" >> "$GITHUB_OUTPUT"
          done
        working-directory: ${{ steps.copy.outputs.path }}

  cache-tests:
    name: Cache tests
    runs-on: ubuntu-latest
    environment:
      name: workshop
      deployment: false
    needs: prepare-cache

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Copy project to separate locations
        id: copy
        run: |
          mkdir "$PROJECT"
          cp -a .workshop "$PROJECT"

          path="prj2-$(openssl rand -hex 8)"
          mkdir "$path"
          cp -a .workshop "$path"
          printf 'path=%s\n' "$path" >> "$GITHUB_OUTPUT"
        env:
          PROJECT: ${{ needs.prepare-cache.outputs.path }}

      - name: Launch workshop in known project
        uses: ./
        with:
          token: ${{ secrets.WORKSHOP_TOKEN }}
          project: ${{ needs.prepare-cache.outputs.path }}
          workshop: cache
          cache: |
            cache:one
            cache:two

      - name: Verify cached data
        run: |
          value="$(workshop run cache read one)"
          [ "$value" = "$ONE" ]
          value="$(workshop run cache read two)"
          [ "$value" = "$TWO" ]
        env:
          ONE: ${{ needs.prepare-cache.outputs.one }}
          TWO: ${{ needs.prepare-cache.outputs.two }}
        working-directory: ${{ needs.prepare-cache.outputs.path }}

      - name: Launch workshop in new project
        uses: ./
        with:
          token: ${{ secrets.WORKSHOP_TOKEN }}
          project: ${{ steps.copy.outputs.path }}
          workshop: cache
          cache: |
            cache:one
            cache:two

      - name: Check cache is empty for new project
        run: |
          workshop run cache empty one
          workshop run cache empty two
        working-directory: ${{ steps.copy.outputs.path }}
